services:
  db:
    image: postgres:16-alpine
    container_name: postgres_prod
    env_file:
      - .env
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 400M

  redis:
    image: redis:7-alpine
    container_name: redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 100M

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
