version: '3.8'  # Добавьте версию в начало файла

services:
  db:
    image: postgres:17-alpine
    container_name: postgres_container
    env_file:
      - ./.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped


  # django:
  #   build: ../django_app
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ../django_app:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - ../infra/.env

  # bot:
  #   build:
  #     context: ..
  #     dockerfile: Dockerfile
  #   command: python -m bot.main
  #   volumes:
  #     - ./bot:/app/bot
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./.env