# Generated by Django 5.1.2 on 2024-11-28 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.category'),
        ),
    ]
