# Generated by Django 5.1.2 on 2024-11-28 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_competition_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.category'),
        ),
    ]
