# Generated by Django 5.1.2 on 2024-11-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_alter_competition_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
