# Generated by Django 5.1.2 on 2024-11-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_competition_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
