# Generated by Django 5.1.2 on 2024-12-05 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_alter_competition_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.categorycompetition'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
