# Generated by Django 5.1.2 on 2024-12-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_categorycompetition_alter_competition_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.categorycompetition'),
        ),
    ]
